### ISSUE TITLE
torchpipe + megatron

### ISSUE THREAD

**Issue by eric-haibin-lin** [kakaobrain/torchgpipe#23]
Can these two work together easily using this codebase? What are the expected hurdles/complications?

**Comment by sublee** [comment]
torchgpipe is a general pipeline parallelism library but there are some restrictions. See: https://torchgpipe.readthedocs.io/en/stable/guide.html#restrictions

To use torchgpipe, you need a simple `nn.Sequential` module. The module must not take care of CUDA devices where the parameters are loaded. If I understand correctly, Megatron might be implemented as a `nn.Sequential` module, but because of its own intra-layer model parallelism layers, probably the module requires specific CUDA devices.
